/**
 * 實價查詢 API
 * 模擬實價登錄資料查詢
 */

export const generateMockRecords = (county, district, keyword) => {
  const mockData = [
    {
      id: 'TX-2024-001',
      address: `${county || '台北市'}${district || '信義區'}${keyword || '信義路'}一段100號`,
      landCategory: '住宅',
      houseType: '電梯大樓',
      transactionDate: '2024-12-15',
      totalPrice: 2800,
      unitAreaPrice: 78.5,
      unitAreaCurrency: '萬元/坪',
      floor: '12/25',
      area: 35.6,
      developer: '遠東建設',
      hasElevator: true,
      latitude: 25.0336,
      longitude: 121.5634,
    },
    {
      id: 'TX-2024-002',
      address: `${county || '台北市'}${district || '大安區'}${keyword || '復興南路'}二段200號`,
      landCategory: '商業',
      houseType: '電梯大樓',
      transactionDate: '2024-11-28',
      totalPrice: 3500,
      unitAreaPrice: 85.2,
      unitAreaCurrency: '萬元/坪',
      floor: '8/18',
      area: 42.3,
      developer: '宏普投資',
      hasElevator: true,
      latitude: 25.0403,
      longitude: 121.5650,
    },
    {
      id: 'TX-2024-003',
      address: `${county || '台北市'}${district || '中山區'}${keyword || '南京東路'}三段55號`,
      landCategory: '住宅',
      houseType: '無電梯公寓',
      transactionDate: '2024-10-10',
      totalPrice: 1500,
      unitAreaPrice: 52.1,
      unitAreaCurrency: '萬元/坪',
      floor: '3/5',
      area: 28.8,
      developer: '無',
      hasElevator: false,
      latitude: 25.0523,
      longitude: 121.5456,
    },
    {
      id: 'TX-2024-004',
      address: `${county || '新北市'}${district || '板橋區'}${keyword || '縣民大道'}88號`,
      landCategory: '住宅',
      houseType: '新建層別屋',
      transactionDate: '2024-09-20',
      totalPrice: 1800,
      unitAreaPrice: 38.6,
      unitAreaCurrency: '萬元/坪',
      floor: '6/22',
      area: 46.5,
      developer: '貴宏建設',
      hasElevator: true,
      latitude: 25.0118,
      longitude: 121.4596,
    },
    {
      id: 'TX-2024-005',
      address: `${county || '新北市'}${district || '新店區'}${keyword || '中興路'}120號`,
      landCategory: '住宅',
      houseType: '透天别墅',
      transactionDate: '2024-08-05',
      totalPrice: 2200,
      unitAreaPrice: 45.3,
      unitAreaCurrency: '萬元/坪',
      floor: '3/4',
      area: 48.6,
      developer: '無',
      hasElevator: false,
      latitude: 24.9750,
      longitude: 121.5325,
    },
    {
      id: 'TX-2024-006',
      address: `${county || '台北市'}${district || '中正區'}${keyword || '重慶南路'}一段90號`,
      landCategory: '商業',
      houseType: '電梯大樓',
      transactionDate: '2024-07-18',
      totalPrice: 4200,
      unitAreaPrice: 92.8,
      unitAreaCurrency: '萬元/坪',
      floor: '10/30',
      area: 45.2,
      developer: '聯聚建設',
      hasElevator: true,
      latitude: 25.0428,
      longitude: 121.5135,
    },
    {
      id: 'TX-2024-007',
      address: `${county || '桃園市'}${district || '桃園區'}${keyword || '市中路'}35號`,
      landCategory: '住宅',
      houseType: '電梯大樓',
      transactionDate: '2024-06-22',
      totalPrice: 980,
      unitAreaPrice: 28.5,
      unitAreaCurrency: '萬元/坪',
      floor: '15/18',
      area: 34.4,
      developer: '台茂建設',
      hasElevator: true,
      latitude: 24.9932,
      longitude: 121.3120,
    },
    {
      id: 'TX-2024-008',
      address: `${county || '台中市'}${district || '西屯區'}${keyword || '臺灣大道'}四段680號`,
      landCategory: '商業',
      houseType: '新建層別屋',
      transactionDate: '2024-05-30',
      totalPrice: 2600,
      unitAreaPrice: 62.3,
      unitAreaCurrency: '萬元/坪',
      floor: '9/20',
      area: 41.7,
      developer: '日茂建設',
      hasElevator: true,
      latitude: 24.1717,
      longitude: 120.6498,
    },
  ]

  return mockData
}

export async function searchLandPrice(params) {
  return generateMockRecords(params.county, params.district, params.keyword)
}
